### ISSUE TITLE
Runtime errors after following install steps

### ISSUE THREAD

**Issue by embirico** [AgoraIO-Community/Agora-Electron-Quickstart#1]
Hi, after cloning the repo, `npm install`, and `npm run dev`, I'm seeing the following errors in the console:

```
Uncaught Error: Cannot find module 'source-map-support/source-map-support.js'
```

and

```
Uncaught Error: Cannot find module 'react'
```

Running node v9.11.2 and npm 5.6.0.

**Comment by plutoless** [comment]
hi @embirico , could you provide your system info pls? e.g. mac/win, 32/64

**Comment by embirico** [comment]
Hi, running on 64-bit windows. Tried the install steps with both 32bit and 64bit node. Let me know if any further info would be useful!

**Comment by menthays** [comment]
Sorry, we cannot reproduce this problem:worried:. Something I can think of:
- node-gyp build failed. But now we do download instead of building c++ addon when install dependencies for our electron sdk.
- Forget to fill in App ID.
- Some other reason that will break `npm install` process.  

So could you check if react was installed properly under node_modules of this project, or provide some other info about this error? Thank you for your attension.
